"""Idea Category id rename

Revision ID: 0ddde4668374
Revises: 46f13728d038
Create Date: 2026-02-14 14:09:23.918193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddde4668374'
down_revision: Union[str, None] = '46f13728d038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ideas', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('Ideas_category_fkey'), 'Ideas', type_='foreignkey')
    op.create_foreign_key(None, 'Ideas', 'Idea_Categorys', ['category_id'], ['id'])
    op.drop_column('Ideas', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ideas', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Ideas', type_='foreignkey')
    op.create_foreign_key(op.f('Ideas_category_fkey'), 'Ideas', 'Idea_Categorys', ['category'], ['id'])
    op.drop_column('Ideas', 'category_id')
    # ### end Alembic commands ###
