"""Idea Status add Public

Revision ID: 46f13728d038
Revises: c1adf7c85f3b
Create Date: 2026-01-03 15:53:34.715512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f13728d038'
down_revision: Union[str, None] = 'c1adf7c85f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Idea_Status', sa.Column('public', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Idea_Status', 'public')
    # ### end Alembic commands ###
