"""Update on delete

Revision ID: 5ac67de54573
Revises: ee59f94a86d8
Create Date: 2026-04-21 22:04:15.537525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac67de54573'
down_revision: Union[str, None] = 'ee59f94a86d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Idea_Images_user_id_fkey'), 'Idea_Images', type_='foreignkey')
    op.create_foreign_key(None, 'Idea_Images', 'Users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('Idea_Likes_user_id_fkey'), 'Idea_Likes', type_='foreignkey')
    op.drop_constraint(op.f('Idea_Likes_idea_id_fkey'), 'Idea_Likes', type_='foreignkey')
    op.create_foreign_key(None, 'Idea_Likes', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Idea_Likes', 'Ideas', ['idea_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Ideas_owner_id_fkey'), 'Ideas', type_='foreignkey')
    op.drop_constraint(op.f('Ideas_status_id_fkey'), 'Ideas', type_='foreignkey')
    op.drop_constraint(op.f('Ideas_category_id_fkey'), 'Ideas', type_='foreignkey')
    op.create_foreign_key(None, 'Ideas', 'Idea_Status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Ideas', 'Idea_Categorys', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Ideas', 'Users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('User_Feedback_user_id_fkey'), 'User_Feedback', type_='foreignkey')
    op.create_foreign_key(None, 'User_Feedback', 'Users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('Users', 'user_group',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('Users_user_group_fkey'), 'Users', type_='foreignkey')
    op.create_foreign_key(None, 'Users', 'User_Groups', ['user_group'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.create_foreign_key(op.f('Users_user_group_fkey'), 'Users', 'User_Groups', ['user_group'], ['id'], ondelete='CASCADE')
    op.alter_column('Users', 'user_group',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'User_Feedback', type_='foreignkey')
    op.create_foreign_key(op.f('User_Feedback_user_id_fkey'), 'User_Feedback', 'Users', ['user_id'], ['id'])
    op.drop_constraint(None, 'Ideas', type_='foreignkey')
    op.drop_constraint(None, 'Ideas', type_='foreignkey')
    op.drop_constraint(None, 'Ideas', type_='foreignkey')
    op.create_foreign_key(op.f('Ideas_category_id_fkey'), 'Ideas', 'Idea_Categorys', ['category_id'], ['id'])
    op.create_foreign_key(op.f('Ideas_status_id_fkey'), 'Ideas', 'Idea_Status', ['status_id'], ['id'])
    op.create_foreign_key(op.f('Ideas_owner_id_fkey'), 'Ideas', 'Users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'Idea_Likes', type_='foreignkey')
    op.drop_constraint(None, 'Idea_Likes', type_='foreignkey')
    op.create_foreign_key(op.f('Idea_Likes_idea_id_fkey'), 'Idea_Likes', 'Ideas', ['idea_id'], ['id'])
    op.create_foreign_key(op.f('Idea_Likes_user_id_fkey'), 'Idea_Likes', 'Users', ['user_id'], ['id'])
    op.drop_constraint(None, 'Idea_Images', type_='foreignkey')
    op.create_foreign_key(op.f('Idea_Images_user_id_fkey'), 'Idea_Images', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
