"""Add Idea Cathegorys

Revision ID: c1adf7c85f3b
Revises: f4f0c41b5bc2
Create Date: 2025-11-29 12:33:44.432986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c1adf7c85f3b'
down_revision: Union[str, None] = 'f4f0c41b5bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Idea_Categorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Ideas', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Ideas', 'Idea_Categorys', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Ideas_category_fkey', 'Ideas', type_='foreignkey')
    op.drop_column('Ideas', 'category')
    op.drop_table('Idea_Categorys')
    # ### end Alembic commands ###
