"""add postgis location to idea

Revision ID: ee59f94a86d8
Revises: 5d2da677663c
Create Date: 2026-04-18 20:45:30.128607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ee59f94a86d8'
down_revision: Union[str, None] = '5d2da677663c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS postgis'))
    op.add_column('Ideas', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.execute(sa.text('UPDATE "Ideas" SET location = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Ideas', 'location')
    # ### end Alembic commands ###
